---
- name: ensure jenkins data volume has the right owner
  file:
    state: directory
    path: "{{ item.mount_point }}"
    owner: "{{ jenkins_systemuser }}"
    group: "{{ jenkins_systemgroup }}"
    mode: '0755'
  with_items: '{{ jenkins_data_vol }}'

- name: ensure jenkins log volume has the right owner
  file:
    state: directory
    path: "{{ item.mount_point }}"
    owner: "{{ jenkins_systemuser }}"
    group: "{{ jenkins_systemgroup }}"
    mode: '0750'
  with_items: '{{ jenkins_log_vol }}'
